services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    env_file:
      - config/.env 
    volumes:
      - .:/app

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
